services:
  factorio:
    image: factoriotools/factorio:stable
    container_name: factorio-server
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - factorio-data:/factorio
    restart: unless-stopped
    environment:
      - RCON_PASSWORD=yourpassword
      - TZ=Europe/Berlin

volumes:
  factorio-data:
